/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrator
 */
public class Chucnangadmin extends javax.swing.JFrame {

    /**
     * Creates new form Chucnangadmin
     */   
    private int id;
    public Chucnangadmin(int id) {
        initComponents();
        this.id=id;
    }

    private Chucnangadmin() {
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btndsuser = new javax.swing.JButton();
        btnquanliuser = new javax.swing.JButton();
        btnnaptien = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        btnttadmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Chọn chức năng");

        btndsuser.setBackground(new java.awt.Color(102, 255, 255));
        btndsuser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btndsuser.setText(" Mở khóa tài khoản");
        btndsuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndsuserActionPerformed(evt);
            }
        });

        btnquanliuser.setBackground(new java.awt.Color(102, 255, 255));
        btnquanliuser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnquanliuser.setText("Quản lí user");
        btnquanliuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanliuserActionPerformed(evt);
            }
        });

        btnnaptien.setBackground(new java.awt.Color(102, 255, 255));
        btnnaptien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnnaptien.setText("Nạp tiền");
        btnnaptien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnaptienActionPerformed(evt);
            }
        });

        btnthoat.setBackground(new java.awt.Color(102, 255, 255));
        btnthoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        btnttadmin.setBackground(new java.awt.Color(102, 255, 255));
        btnttadmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnttadmin.setText("Thông tin admin");
        btnttadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnttadminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnttadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndsuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnquanliuser, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(btnnaptien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnthoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnttadmin)
                .addGap(27, 27, 27)
                .addComponent(btndsuser)
                .addGap(27, 27, 27)
                .addComponent(btnquanliuser)
                .addGap(27, 27, 27)
                .addComponent(btnnaptien)
                .addGap(58, 58, 58)
                .addComponent(btnthoat)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        new Choose().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnthoatActionPerformed

    private void btnquanliuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanliuserActionPerformed
        try {
            // TODO add your handling code here:
            new QuanliUser(id).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Chucnangadmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnquanliuserActionPerformed

    private void btnnaptienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnaptienActionPerformed
        // TODO add your handling code here:
        new Naptien(id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnnaptienActionPerformed

    private void btnttadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnttadminActionPerformed
        try {
            // TODO add your handling code here:
            new Thongtinadmin(id).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Chucnangadmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnttadminActionPerformed

    private void btndsuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndsuserActionPerformed
        // TODO add your handling code here:
        new MokhoaUser(id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndsuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chucnangadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chucnangadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chucnangadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chucnangadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chucnangadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndsuser;
    private javax.swing.JButton btnnaptien;
    private javax.swing.JButton btnquanliuser;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btnttadmin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
