/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class ChuyenTienUser extends javax.swing.JFrame {

    /**
     * Creates new form ChuyenTienUser
     */
    private int stk;

    public ChuyenTienUser(int stk) {
        initComponents();
        this.stk = stk;
    }

    private ChuyenTienUser() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttk = new javax.swing.JTextField();
        txttien = new javax.swing.JTextField();
        btnxn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Chuyển Tiền");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nhập số tk cần chuyển : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nhập số tiền cẩn chuyển : ");

        txttk.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        txttien.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        btnxn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnxn.setText("Xác Nhận");
        btnxn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxnActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton2.setText("Quay Lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnxn)
                        .addGap(73, 73, 73)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txttk, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(54, 54, 54)
                                .addComponent(txttien, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxn)
                    .addComponent(jButton2))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnxnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxnActionPerformed
        // TODO add your handling code here:
        Database db = new Database();
        Connection c = db.getConnection();
        String sql = "SELECT * FROM `user` WHERE stk=" + stk;
        String sql10 = "SELECT * FROM `user` WHERE stk=" + txttk.getText();
        ResultSet r10;
        try {
            r10 = c.createStatement().executeQuery(sql10);
            if (!r10.next()) {
                JOptionPane.showMessageDialog(null, "Không tìm thấy tài khoản cân chuyển");
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChuyenTienUser.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            ResultSet r = c.createStatement().executeQuery(sql);
            while (r.next()) {
                if (r.getDouble("sodu") - Integer.parseInt(txttien.getText()) >= 50000) {
                    String sql1 = "UPDATE user SET sodu=sodu-" + txttien.getText() + " WHERE stk=" + stk;
                    String sql2 = "UPDATE user SET sodu=sodu+" + txttien.getText() + " WHERE stk=" + txttk.getText();
                    Statement st = c.createStatement();
                    st.execute(sql1);
                    JOptionPane.showMessageDialog(null, "Chuyển tiền thành công");
                    File f = new File("lichsu" + stk + ".txt");
                    FileWriter fw;
                    File f1 = new File("lichsu" + txttk.getText() + ".txt");
                    FileWriter fw1;
                    
                    File ftkc = new File("tkchuyen" + stk + ".txt");
                    FileWriter fwtkc;
                    File ftkdc = new File("tkduocchuyen" + txttk.getText() + ".txt");
                    FileWriter fwtkdc;
                    try {
                        fw = new FileWriter(f, true);
                        BufferedWriter bw = new BufferedWriter(fw);
                        bw.write("Vào lúc " + java.time.LocalDateTime.now() + " quý khách đã chuyển " + txttien.getText() + " đồng vào tài khoản " + txttk.getText() + ".");
                        bw.newLine();
                        bw.close();
                        
                        fw1 = new FileWriter(f1, true);
                        BufferedWriter bw1 = new BufferedWriter(fw1);
                        bw1.write("Vào lúc " + java.time.LocalDateTime.now() + " quý khách đã được chuyển " + txttien.getText() + " đồng vào tài khoản bởi tài khoản " + stk + ".");
                        bw1.newLine();
                        bw1.close();
                        
                        fwtkc = new FileWriter(ftkc, true);
                        BufferedWriter bwtkc = new BufferedWriter(fwtkc);
                        bwtkc.write(java.time.LocalDateTime.now().getMonthValue()+"-"+txttien.getText());
                        bwtkc.newLine();
                        bwtkc.close();
                        
                        fwtkdc = new FileWriter(ftkdc, true);
                        BufferedWriter bwtkdc = new BufferedWriter(fwtkdc);
                        bwtkdc.write(java.time.LocalDateTime.now().getMonthValue()+"-"+txttien.getText());
                        bwtkdc.newLine();
                        bwtkdc.close();
                    } catch (IOException ex) {
                        Logger.getLogger(Ruttien.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Không đủ tiền để chuyển");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(MokhoaUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnxnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ChucnangUser(stk).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChuyenTienUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChuyenTienUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChuyenTienUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChuyenTienUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChuyenTienUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnxn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txttien;
    private javax.swing.JTextField txttk;
    // End of variables declaration//GEN-END:variables
}
